version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - test-net
    volumes:
      - mongo-data:/data/db

networks:
  test-net:
    driver: bridge
    external: false

volumes:
  mongo-data:
    name: "mongo-data"